import { Registry } from "@/registry/schema"

export const ui: Registry = [
  {
    name: "accordion",
    type: "components:ui",
    dependencies: ["@radix-ui/react-accordion"],
    files: [
      "ui/accordion.tsx",
      "ui/accordion.scss",
      "ui/accordion.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "alert",
    type: "components:ui",
    files: [
      "ui/alert.tsx",
      "ui/alert.scss",
      "ui/alert.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "alert-dialog",
    type: "components:ui",
    dependencies: ["@radix-ui/react-alert-dialog"],
    registryDependencies: ["button"],
    files: [
      "ui/alert-dialog.tsx",
      "ui/alert-dialog.scss",
      "ui/alert-dialog.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "aspect-ratio",
    type: "components:ui",
    dependencies: ["@radix-ui/react-aspect-ratio"],
    files: [
      "ui/aspect-ratio.tsx",
      "ui/aspect-ratio.scss",
      "ui/aspect-ratio.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "avatar",
    type: "components:ui",
    dependencies: ["@radix-ui/react-avatar"],
    files: [
      "ui/avatar.tsx",
      "ui/avatar.scss",
      "ui/avatar.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "badge",
    type: "components:ui",
    files: [
      "ui/badge.tsx",
      "ui/badge.scss",
      "ui/badge.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "breadcrumb",
    type: "components:ui",
    dependencies: ["@radix-ui/react-slot"],
    files: [
      "ui/breadcrumb.tsx",
      "ui/breadcrumb.scss",
      "ui/breadcrumb.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "button",
    type: "components:ui",
    dependencies: ["@radix-ui/react-slot"],
    files: [
      "ui/button.tsx",
      "ui/button.scss",
      "ui/button.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "calendar",
    type: "components:ui",
    dependencies: ["react-day-picker", "date-fns"],
    registryDependencies: ["button"],
    files: [
      "ui/calendar.tsx",
      "ui/calendar.scss",
      "ui/calendar.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "card",
    type: "components:ui",
    files: [
      "ui/card.tsx",
      "ui/card.scss",
      "ui/card.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "carousel",
    type: "components:ui",
    files: [
      "ui/carousel.tsx",
      "ui/carousel.scss",
      "ui/carousel.stories.tsx",
      "ui/index.ts",
    ],
    registryDependencies: ["button"],
    dependencies: ["embla-carousel-react"],
  },
  {
    name: "checkbox",
    type: "components:ui",
    dependencies: ["@radix-ui/react-checkbox"],
    files: [
      "ui/checkbox.tsx",
      "ui/checkbox.scss",
      "ui/checkbox.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "collapsible",
    type: "components:ui",
    dependencies: ["@radix-ui/react-collapsible"],
    files: [
      "ui/collapsible.tsx",
      "ui/collapsible.scss",
      "ui/collapsible.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "command",
    type: "components:ui",
    dependencies: ["cmdk"],
    registryDependencies: ["dialog"],
    files: [
      "ui/command.tsx",
      "ui/command.scss",
      "ui/command.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "context-menu",
    type: "components:ui",
    dependencies: ["@radix-ui/react-context-menu"],
    files: [
      "ui/context-menu.tsx",
      "ui/context-menu.scss",
      "ui/context-menu.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "dialog",
    type: "components:ui",
    dependencies: ["@radix-ui/react-dialog"],
    files: [
      "ui/dialog.tsx",
      "ui/dialog.scss",
      "ui/dialog.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "drawer",
    type: "components:ui",
    dependencies: ["vaul", "@radix-ui/react-dialog"],
    files: [
      "ui/drawer.tsx",
      "ui/drawer.scss",
      "ui/drawer.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "dropdown-menu",
    type: "components:ui",
    dependencies: ["@radix-ui/react-dropdown-menu"],
    files: [
      "ui/dropdown-menu.tsx",
      "ui/dropdown-menu.scss",
      "ui/dropdown-menu.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "form",
    type: "components:ui",
    dependencies: [
      "@radix-ui/react-label",
      "@radix-ui/react-slot",
      "@hookform/resolvers",
      "zod",
      "react-hook-form",
    ],
    registryDependencies: ["button", "label"],
    files: [
      "ui/form.tsx",
      "ui/form.scss",
      "ui/form.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "hover-card",
    type: "components:ui",
    dependencies: ["@radix-ui/react-hover-card"],
    files: [
      "ui/hover-card.tsx",
      "ui/hover-card.scss",
      "ui/hover-card.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "input",
    type: "components:ui",
    files: [
      "ui/input.tsx",
      "ui/input.scss",
      "ui/input.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "input-otp",
    type: "components:ui",
    dependencies: ["input-otp"],
    files: [
      "ui/input-otp.tsx",
      "ui/input-otp.scss",
      "ui/input-otp.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "label",
    type: "components:ui",
    dependencies: ["@radix-ui/react-label"],
    files: [
      "ui/label.tsx",
      "ui/label.scss",
      "ui/label.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "menubar",
    type: "components:ui",
    dependencies: ["@radix-ui/react-menubar"],
    files: [
      "ui/menubar.tsx",
      "ui/menubar.scss",
      "ui/menubar.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "navigation-menu",
    type: "components:ui",
    dependencies: ["@radix-ui/react-navigation-menu"],
    files: [
      "ui/navigation-menu.tsx",
      "ui/navigation-menu.scss",
      "ui/navigation-menu.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "pagination",
    type: "components:ui",
    registryDependencies: ["button"],
    files: [
      "ui/pagination.tsx",
      "ui/pagination.scss",
      "ui/pagination.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "popover",
    type: "components:ui",
    dependencies: ["@radix-ui/react-popover"],
    files: [
      "ui/popover.tsx",
      "ui/popover.scss",
      "ui/popover.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "progress",
    type: "components:ui",
    dependencies: ["@radix-ui/react-progress"],
    files: [
      "ui/progress.tsx",
      "ui/progress.scss",
      "ui/progress.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "radio-group",
    type: "components:ui",
    dependencies: ["@radix-ui/react-radio-group"],
    files: [
      "ui/radio-group.tsx",
      "ui/radio-group.scss",
      "ui/radio-group.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "resizable",
    type: "components:ui",
    dependencies: ["react-resizable-panels"],
    files: [
      "ui/resizable.tsx",
      "ui/resizable.scss",
      "ui/resizable.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "scroll-area",
    type: "components:ui",
    dependencies: ["@radix-ui/react-scroll-area"],
    files: [
      "ui/scroll-area.tsx",
      "ui/scroll-area.scss",
      "ui/scroll-area.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "select",
    type: "components:ui",
    dependencies: ["@radix-ui/react-select"],
    files: [
      "ui/select.tsx",
      "ui/select.scss",
      "ui/select.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "separator",
    type: "components:ui",
    dependencies: ["@radix-ui/react-separator"],
    files: [
      "ui/separator.tsx",
      "ui/separator.scss",
      "ui/separator.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "sheet",
    type: "components:ui",
    dependencies: ["@radix-ui/react-dialog"],
    files: [
      "ui/sheet.tsx",
      "ui/sheet.scss",
      "ui/sheet.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "skeleton",
    type: "components:ui",
    files: [
      "ui/skeleton.tsx",
      "ui/skeleton.scss",
      "ui/skeleton.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "slider",
    type: "components:ui",
    dependencies: ["@radix-ui/react-slider"],
    files: [
      "ui/slider.tsx",
      "ui/slider.scss",
      "ui/slider.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "sonner",
    type: "components:ui",
    dependencies: ["sonner", "next-themes"],
    files: ["ui/sonner.tsx", "ui/sonner.stories.tsx", "ui/index.ts"],
  },
  {
    name: "switch",
    type: "components:ui",
    dependencies: ["@radix-ui/react-switch"],
    files: [
      "ui/switch.tsx",
      "ui/switch.scss",
      "ui/switch.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "table",
    type: "components:ui",
    files: [
      "ui/table.tsx",
      "ui/table.scss",
      "ui/table.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "tabs",
    type: "components:ui",
    dependencies: ["@radix-ui/react-tabs"],
    files: [
      "ui/tabs.tsx",
      "ui/tabs.scss",
      "ui/tabs.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "textarea",
    type: "components:ui",
    files: [
      "ui/textarea.tsx",
      "ui/textarea.scss",
      "ui/textarea.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "toast",
    type: "components:ui",
    dependencies: ["@radix-ui/react-toast"],
    files: [
      "ui/toast.tsx",
      "ui/use-toast.ts",
      "ui/toaster.tsx",
      "ui/toast.scss",
      "ui/toast.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "toggle",
    type: "components:ui",
    dependencies: ["@radix-ui/react-toggle"],
    files: [
      "ui/toggle.tsx",
      "ui/toggle.scss",
      "ui/toggle.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "toggle-group",
    type: "components:ui",
    dependencies: ["@radix-ui/react-toggle-group"],
    registryDependencies: ["toggle"],
    files: [
      "ui/toggle-group.tsx",
      "ui/toggle-group.scss",
      "ui/toggle-group.stories.tsx",
      "ui/index.ts",
    ],
  },
  {
    name: "tooltip",
    type: "components:ui",
    dependencies: ["@radix-ui/react-tooltip"],
    files: [
      "ui/tooltip.tsx",
      "ui/tooltip.scss",
      "ui/tooltip.stories.tsx",
      "ui/tooltip.types.ts",
      "ui/index.ts",
    ],
  },
]
