// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "scss": {
    "accordion": {
      name: "accordion",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/accordion")),
      source: "",
      files: ["registry/scss/ui/accordion/accordion.tsx","registry/scss/ui/accordion/accordion.scss","registry/scss/ui/accordion/accordion.stories.tsx","registry/scss/ui/accordion/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "alert": {
      name: "alert",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/alert")),
      source: "",
      files: ["registry/scss/ui/alert/alert.tsx","registry/scss/ui/alert/alert.scss","registry/scss/ui/alert/alert.stories.tsx","registry/scss/ui/alert/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "alert-dialog": {
      name: "alert-dialog",
      type: "components:ui",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/ui/alert-dialog")),
      source: "",
      files: ["registry/scss/ui/alert-dialog/alert-dialog.tsx","registry/scss/ui/alert-dialog/alert-dialog.scss","registry/scss/ui/alert-dialog/alert-dialog.stories.tsx","registry/scss/ui/alert-dialog/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "aspect-ratio": {
      name: "aspect-ratio",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/aspect-ratio")),
      source: "",
      files: ["registry/scss/ui/aspect-ratio/aspect-ratio.tsx","registry/scss/ui/aspect-ratio/aspect-ratio.scss","registry/scss/ui/aspect-ratio/aspect-ratio.stories.tsx","registry/scss/ui/aspect-ratio/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "avatar": {
      name: "avatar",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/avatar")),
      source: "",
      files: ["registry/scss/ui/avatar/avatar.tsx","registry/scss/ui/avatar/avatar.scss","registry/scss/ui/avatar/avatar.stories.tsx","registry/scss/ui/avatar/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "badge": {
      name: "badge",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/badge")),
      source: "",
      files: ["registry/scss/ui/badge/badge.tsx","registry/scss/ui/badge/badge.scss","registry/scss/ui/badge/badge.stories.tsx","registry/scss/ui/badge/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "breadcrumb": {
      name: "breadcrumb",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/breadcrumb")),
      source: "",
      files: ["registry/scss/ui/breadcrumb/breadcrumb.tsx","registry/scss/ui/breadcrumb/breadcrumb.scss","registry/scss/ui/breadcrumb/breadcrumb.stories.tsx","registry/scss/ui/breadcrumb/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button": {
      name: "button",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/button")),
      source: "",
      files: ["registry/scss/ui/button/button.tsx","registry/scss/ui/button/button.scss","registry/scss/ui/button/button.stories.tsx","registry/scss/ui/button/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "calendar": {
      name: "calendar",
      type: "components:ui",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/ui/calendar")),
      source: "",
      files: ["registry/scss/ui/calendar/calendar.tsx","registry/scss/ui/calendar/calendar.scss","registry/scss/ui/calendar/calendar.stories.tsx","registry/scss/ui/calendar/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "card": {
      name: "card",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/card")),
      source: "",
      files: ["registry/scss/ui/card/card.tsx","registry/scss/ui/card/card.scss","registry/scss/ui/card/card.stories.tsx","registry/scss/ui/card/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "carousel": {
      name: "carousel",
      type: "components:ui",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/ui/carousel")),
      source: "",
      files: ["registry/scss/ui/carousel/carousel.tsx","registry/scss/ui/carousel/carousel.scss","registry/scss/ui/carousel/carousel.stories.tsx","registry/scss/ui/carousel/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "checkbox": {
      name: "checkbox",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/checkbox")),
      source: "",
      files: ["registry/scss/ui/checkbox/checkbox.tsx","registry/scss/ui/checkbox/checkbox.scss","registry/scss/ui/checkbox/checkbox.stories.tsx","registry/scss/ui/checkbox/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "collapsible": {
      name: "collapsible",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/collapsible")),
      source: "",
      files: ["registry/scss/ui/collapsible/collapsible.tsx","registry/scss/ui/collapsible/collapsible.scss","registry/scss/ui/collapsible/collapsible.stories.tsx","registry/scss/ui/collapsible/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "command": {
      name: "command",
      type: "components:ui",
      registryDependencies: ["dialog"],
      component: React.lazy(() => import("@/registry/scss/ui/command")),
      source: "",
      files: ["registry/scss/ui/command/command.tsx","registry/scss/ui/command/command.scss","registry/scss/ui/command/command.stories.tsx","registry/scss/ui/command/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "context-menu": {
      name: "context-menu",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/context-menu")),
      source: "",
      files: ["registry/scss/ui/context-menu/context-menu.tsx","registry/scss/ui/context-menu/context-menu.scss","registry/scss/ui/context-menu/context-menu.stories.tsx","registry/scss/ui/context-menu/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dialog": {
      name: "dialog",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/dialog")),
      source: "",
      files: ["registry/scss/ui/dialog/dialog.tsx","registry/scss/ui/dialog/dialog.scss","registry/scss/ui/dialog/dialog.stories.tsx","registry/scss/ui/dialog/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "drawer": {
      name: "drawer",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/drawer")),
      source: "",
      files: ["registry/scss/ui/drawer/drawer.tsx","registry/scss/ui/drawer/drawer.scss","registry/scss/ui/drawer/drawer.stories.tsx","registry/scss/ui/drawer/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/dropdown-menu")),
      source: "",
      files: ["registry/scss/ui/dropdown-menu/dropdown-menu.tsx","registry/scss/ui/dropdown-menu/dropdown-menu.scss","registry/scss/ui/dropdown-menu/dropdown-menu.stories.tsx","registry/scss/ui/dropdown-menu/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "form": {
      name: "form",
      type: "components:ui",
      registryDependencies: ["button","label"],
      component: React.lazy(() => import("@/registry/scss/ui/form")),
      source: "",
      files: ["registry/scss/ui/form/form.tsx","registry/scss/ui/form/form.scss","registry/scss/ui/form/form.stories.tsx","registry/scss/ui/form/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "hover-card": {
      name: "hover-card",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/hover-card")),
      source: "",
      files: ["registry/scss/ui/hover-card/hover-card.tsx","registry/scss/ui/hover-card/hover-card.scss","registry/scss/ui/hover-card/hover-card.stories.tsx","registry/scss/ui/hover-card/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input": {
      name: "input",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/input")),
      source: "",
      files: ["registry/scss/ui/input/input.tsx","registry/scss/ui/input/input.scss","registry/scss/ui/input/input.stories.tsx","registry/scss/ui/input/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input-otp": {
      name: "input-otp",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/input-otp")),
      source: "",
      files: ["registry/scss/ui/input-otp/input-otp.tsx","registry/scss/ui/input-otp/input-otp.scss","registry/scss/ui/input-otp/input-otp.stories.tsx","registry/scss/ui/input-otp/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "label": {
      name: "label",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/label")),
      source: "",
      files: ["registry/scss/ui/label/label.tsx","registry/scss/ui/label/label.scss","registry/scss/ui/label/label.stories.tsx","registry/scss/ui/label/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "menubar": {
      name: "menubar",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/menubar")),
      source: "",
      files: ["registry/scss/ui/menubar/menubar.tsx","registry/scss/ui/menubar/menubar.scss","registry/scss/ui/menubar/menubar.stories.tsx","registry/scss/ui/menubar/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "navigation-menu": {
      name: "navigation-menu",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/navigation-menu")),
      source: "",
      files: ["registry/scss/ui/navigation-menu/navigation-menu.tsx","registry/scss/ui/navigation-menu/navigation-menu.scss","registry/scss/ui/navigation-menu/navigation-menu.stories.tsx","registry/scss/ui/navigation-menu/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "pagination": {
      name: "pagination",
      type: "components:ui",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/ui/pagination")),
      source: "",
      files: ["registry/scss/ui/pagination/pagination.tsx","registry/scss/ui/pagination/pagination.scss","registry/scss/ui/pagination/pagination.stories.tsx","registry/scss/ui/pagination/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "popover": {
      name: "popover",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/popover")),
      source: "",
      files: ["registry/scss/ui/popover/popover.tsx","registry/scss/ui/popover/popover.scss","registry/scss/ui/popover/popover.stories.tsx","registry/scss/ui/popover/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "progress": {
      name: "progress",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/progress")),
      source: "",
      files: ["registry/scss/ui/progress/progress.tsx","registry/scss/ui/progress/progress.scss","registry/scss/ui/progress/progress.stories.tsx","registry/scss/ui/progress/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "radio-group": {
      name: "radio-group",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/radio-group")),
      source: "",
      files: ["registry/scss/ui/radio-group/radio-group.tsx","registry/scss/ui/radio-group/radio-group.scss","registry/scss/ui/radio-group/radio-group.stories.tsx","registry/scss/ui/radio-group/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "resizable": {
      name: "resizable",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/resizable")),
      source: "",
      files: ["registry/scss/ui/resizable/resizable.tsx","registry/scss/ui/resizable/resizable.scss","registry/scss/ui/resizable/resizable.stories.tsx","registry/scss/ui/resizable/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "scroll-area": {
      name: "scroll-area",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/scroll-area")),
      source: "",
      files: ["registry/scss/ui/scroll-area/scroll-area.tsx","registry/scss/ui/scroll-area/scroll-area.scss","registry/scss/ui/scroll-area/scroll-area.stories.tsx","registry/scss/ui/scroll-area/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "select": {
      name: "select",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/select")),
      source: "",
      files: ["registry/scss/ui/select/select.tsx","registry/scss/ui/select/select.scss","registry/scss/ui/select/select.stories.tsx","registry/scss/ui/select/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "separator": {
      name: "separator",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/separator")),
      source: "",
      files: ["registry/scss/ui/separator/separator.tsx","registry/scss/ui/separator/separator.scss","registry/scss/ui/separator/separator.stories.tsx","registry/scss/ui/separator/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sheet": {
      name: "sheet",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/sheet")),
      source: "",
      files: ["registry/scss/ui/sheet/sheet.tsx","registry/scss/ui/sheet/sheet.scss","registry/scss/ui/sheet/sheet.stories.tsx","registry/scss/ui/sheet/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "skeleton": {
      name: "skeleton",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/skeleton")),
      source: "",
      files: ["registry/scss/ui/skeleton/skeleton.tsx","registry/scss/ui/skeleton/skeleton.scss","registry/scss/ui/skeleton/skeleton.stories.tsx","registry/scss/ui/skeleton/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "slider": {
      name: "slider",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/slider")),
      source: "",
      files: ["registry/scss/ui/slider/slider.tsx","registry/scss/ui/slider/slider.scss","registry/scss/ui/slider/slider.stories.tsx","registry/scss/ui/slider/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sonner": {
      name: "sonner",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/sonner")),
      source: "",
      files: ["registry/scss/ui/sonner/sonner.tsx","registry/scss/ui/sonner/sonner.stories.tsx","registry/scss/ui/sonner/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "switch": {
      name: "switch",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/switch")),
      source: "",
      files: ["registry/scss/ui/switch/switch.tsx","registry/scss/ui/switch/switch.scss","registry/scss/ui/switch/switch.stories.tsx","registry/scss/ui/switch/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "table": {
      name: "table",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/table")),
      source: "",
      files: ["registry/scss/ui/table/table.tsx","registry/scss/ui/table/table.scss","registry/scss/ui/table/table.stories.tsx","registry/scss/ui/table/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tabs": {
      name: "tabs",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/tabs")),
      source: "",
      files: ["registry/scss/ui/tabs/tabs.tsx","registry/scss/ui/tabs/tabs.scss","registry/scss/ui/tabs/tabs.stories.tsx","registry/scss/ui/tabs/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "textarea": {
      name: "textarea",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/textarea")),
      source: "",
      files: ["registry/scss/ui/textarea/textarea.tsx","registry/scss/ui/textarea/textarea.scss","registry/scss/ui/textarea/textarea.stories.tsx","registry/scss/ui/textarea/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toast": {
      name: "toast",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/toast")),
      source: "",
      files: ["registry/scss/ui/toast/toast.tsx","registry/scss/ui/toast/use-toast.ts","registry/scss/ui/toast/toaster.tsx","registry/scss/ui/toast/toast.scss","registry/scss/ui/toast/toast.stories.tsx","registry/scss/ui/toast/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle": {
      name: "toggle",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/toggle")),
      source: "",
      files: ["registry/scss/ui/toggle/toggle.tsx","registry/scss/ui/toggle/toggle.scss","registry/scss/ui/toggle/toggle.stories.tsx","registry/scss/ui/toggle/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle-group": {
      name: "toggle-group",
      type: "components:ui",
      registryDependencies: ["toggle"],
      component: React.lazy(() => import("@/registry/scss/ui/toggle-group")),
      source: "",
      files: ["registry/scss/ui/toggle-group/toggle-group.tsx","registry/scss/ui/toggle-group/toggle-group.scss","registry/scss/ui/toggle-group/toggle-group.stories.tsx","registry/scss/ui/toggle-group/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tooltip": {
      name: "tooltip",
      type: "components:ui",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/ui/tooltip")),
      source: "",
      files: ["registry/scss/ui/tooltip/tooltip.tsx","registry/scss/ui/tooltip/tooltip.scss","registry/scss/ui/tooltip/tooltip.stories.tsx","registry/scss/ui/tooltip/tooltip.types.ts","registry/scss/ui/tooltip/index.ts"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "accordion-demo": {
      name: "accordion-demo",
      type: "components:example",
      registryDependencies: ["accordion"],
      component: React.lazy(() => import("@/registry/scss/example/accordion-demo")),
      source: "",
      files: ["registry/scss/example/accordion-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "alert-demo": {
      name: "alert-demo",
      type: "components:example",
      registryDependencies: ["alert"],
      component: React.lazy(() => import("@/registry/scss/example/alert-demo")),
      source: "",
      files: ["registry/scss/example/alert-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "alert-destructive": {
      name: "alert-destructive",
      type: "components:example",
      registryDependencies: ["alert"],
      component: React.lazy(() => import("@/registry/scss/example/alert-destructive")),
      source: "",
      files: ["registry/scss/example/alert-destructive.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "alert-dialog-demo": {
      name: "alert-dialog-demo",
      type: "components:example",
      registryDependencies: ["alert-dialog","button"],
      component: React.lazy(() => import("@/registry/scss/example/alert-dialog-demo")),
      source: "",
      files: ["registry/scss/example/alert-dialog-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "aspect-ratio-demo": {
      name: "aspect-ratio-demo",
      type: "components:example",
      registryDependencies: ["aspect-ratio"],
      component: React.lazy(() => import("@/registry/scss/example/aspect-ratio-demo")),
      source: "",
      files: ["registry/scss/example/aspect-ratio-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "avatar-demo": {
      name: "avatar-demo",
      type: "components:example",
      registryDependencies: ["avatar"],
      component: React.lazy(() => import("@/registry/scss/example/avatar-demo")),
      source: "",
      files: ["registry/scss/example/avatar-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "badge-demo": {
      name: "badge-demo",
      type: "components:example",
      registryDependencies: ["badge"],
      component: React.lazy(() => import("@/registry/scss/example/badge-demo")),
      source: "",
      files: ["registry/scss/example/badge-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "badge-destructive": {
      name: "badge-destructive",
      type: "components:example",
      registryDependencies: ["badge"],
      component: React.lazy(() => import("@/registry/scss/example/badge-destructive")),
      source: "",
      files: ["registry/scss/example/badge-destructive.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "badge-outline": {
      name: "badge-outline",
      type: "components:example",
      registryDependencies: ["badge"],
      component: React.lazy(() => import("@/registry/scss/example/badge-outline")),
      source: "",
      files: ["registry/scss/example/badge-outline.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "badge-secondary": {
      name: "badge-secondary",
      type: "components:example",
      registryDependencies: ["badge"],
      component: React.lazy(() => import("@/registry/scss/example/badge-secondary")),
      source: "",
      files: ["registry/scss/example/badge-secondary.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "breadcrumb-demo": {
      name: "breadcrumb-demo",
      type: "components:example",
      registryDependencies: ["breadcrumb"],
      component: React.lazy(() => import("@/registry/scss/example/breadcrumb-demo")),
      source: "",
      files: ["registry/scss/example/breadcrumb-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "breadcrumb-separator": {
      name: "breadcrumb-separator",
      type: "components:example",
      registryDependencies: ["breadcrumb"],
      component: React.lazy(() => import("@/registry/scss/example/breadcrumb-separator")),
      source: "",
      files: ["registry/scss/example/breadcrumb-separator.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "breadcrumb-dropdown": {
      name: "breadcrumb-dropdown",
      type: "components:example",
      registryDependencies: ["breadcrumb"],
      component: React.lazy(() => import("@/registry/scss/example/breadcrumb-dropdown")),
      source: "",
      files: ["registry/scss/example/breadcrumb-dropdown.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "breadcrumb-ellipsis": {
      name: "breadcrumb-ellipsis",
      type: "components:example",
      registryDependencies: ["breadcrumb"],
      component: React.lazy(() => import("@/registry/scss/example/breadcrumb-ellipsis")),
      source: "",
      files: ["registry/scss/example/breadcrumb-ellipsis.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "breadcrumb-link": {
      name: "breadcrumb-link",
      type: "components:example",
      registryDependencies: ["breadcrumb"],
      component: React.lazy(() => import("@/registry/scss/example/breadcrumb-link")),
      source: "",
      files: ["registry/scss/example/breadcrumb-link.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "breadcrumb-responsive": {
      name: "breadcrumb-responsive",
      type: "components:example",
      registryDependencies: ["breadcrumb"],
      component: React.lazy(() => import("@/registry/scss/example/breadcrumb-responsive")),
      source: "",
      files: ["registry/scss/example/breadcrumb-responsive.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-demo": {
      name: "button-demo",
      type: "components:example",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/example/button-demo")),
      source: "",
      files: ["registry/scss/example/button-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-secondary": {
      name: "button-secondary",
      type: "components:example",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/example/button-secondary")),
      source: "",
      files: ["registry/scss/example/button-secondary.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-destructive": {
      name: "button-destructive",
      type: "components:example",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/example/button-destructive")),
      source: "",
      files: ["registry/scss/example/button-destructive.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-outline": {
      name: "button-outline",
      type: "components:example",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/example/button-outline")),
      source: "",
      files: ["registry/scss/example/button-outline.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-ghost": {
      name: "button-ghost",
      type: "components:example",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/example/button-ghost")),
      source: "",
      files: ["registry/scss/example/button-ghost.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-link": {
      name: "button-link",
      type: "components:example",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/example/button-link")),
      source: "",
      files: ["registry/scss/example/button-link.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-with-icon": {
      name: "button-with-icon",
      type: "components:example",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/example/button-with-icon")),
      source: "",
      files: ["registry/scss/example/button-with-icon.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-loading": {
      name: "button-loading",
      type: "components:example",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/example/button-loading")),
      source: "",
      files: ["registry/scss/example/button-loading.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-icon": {
      name: "button-icon",
      type: "components:example",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/example/button-icon")),
      source: "",
      files: ["registry/scss/example/button-icon.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "button-as-child": {
      name: "button-as-child",
      type: "components:example",
      registryDependencies: ["button"],
      component: React.lazy(() => import("@/registry/scss/example/button-as-child")),
      source: "",
      files: ["registry/scss/example/button-as-child.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "calendar-demo": {
      name: "calendar-demo",
      type: "components:example",
      registryDependencies: ["calendar"],
      component: React.lazy(() => import("@/registry/scss/example/calendar-demo")),
      source: "",
      files: ["registry/scss/example/calendar-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "calendar-form": {
      name: "calendar-form",
      type: "components:example",
      registryDependencies: ["calendar","form","popover"],
      component: React.lazy(() => import("@/registry/scss/example/calendar-form")),
      source: "",
      files: ["registry/scss/example/calendar-form.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "card-demo": {
      name: "card-demo",
      type: "components:example",
      registryDependencies: ["card","button","switch"],
      component: React.lazy(() => import("@/registry/scss/example/card-demo")),
      source: "",
      files: ["registry/scss/example/card-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "card-with-form": {
      name: "card-with-form",
      type: "components:example",
      registryDependencies: ["button","card","input","label","select"],
      component: React.lazy(() => import("@/registry/scss/example/card-with-form")),
      source: "",
      files: ["registry/scss/example/card-with-form.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "carousel-demo": {
      name: "carousel-demo",
      type: "components:example",
      registryDependencies: ["carousel"],
      component: React.lazy(() => import("@/registry/scss/example/carousel-demo")),
      source: "",
      files: ["registry/scss/example/carousel-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "carousel-size": {
      name: "carousel-size",
      type: "components:example",
      registryDependencies: ["carousel"],
      component: React.lazy(() => import("@/registry/scss/example/carousel-size")),
      source: "",
      files: ["registry/scss/example/carousel-size.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "carousel-spacing": {
      name: "carousel-spacing",
      type: "components:example",
      registryDependencies: ["carousel"],
      component: React.lazy(() => import("@/registry/scss/example/carousel-spacing")),
      source: "",
      files: ["registry/scss/example/carousel-spacing.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "carousel-orientation": {
      name: "carousel-orientation",
      type: "components:example",
      registryDependencies: ["carousel"],
      component: React.lazy(() => import("@/registry/scss/example/carousel-orientation")),
      source: "",
      files: ["registry/scss/example/carousel-orientation.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "carousel-api": {
      name: "carousel-api",
      type: "components:example",
      registryDependencies: ["carousel"],
      component: React.lazy(() => import("@/registry/scss/example/carousel-api")),
      source: "",
      files: ["registry/scss/example/carousel-api.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "carousel-plugin": {
      name: "carousel-plugin",
      type: "components:example",
      registryDependencies: ["carousel"],
      component: React.lazy(() => import("@/registry/scss/example/carousel-plugin")),
      source: "",
      files: ["registry/scss/example/carousel-plugin.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "checkbox-demo": {
      name: "checkbox-demo",
      type: "components:example",
      registryDependencies: ["checkbox"],
      component: React.lazy(() => import("@/registry/scss/example/checkbox-demo")),
      source: "",
      files: ["registry/scss/example/checkbox-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "checkbox-disabled": {
      name: "checkbox-disabled",
      type: "components:example",
      registryDependencies: ["checkbox"],
      component: React.lazy(() => import("@/registry/scss/example/checkbox-disabled")),
      source: "",
      files: ["registry/scss/example/checkbox-disabled.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "checkbox-form-multiple": {
      name: "checkbox-form-multiple",
      type: "components:example",
      registryDependencies: ["checkbox","form"],
      component: React.lazy(() => import("@/registry/scss/example/checkbox-form-multiple")),
      source: "",
      files: ["registry/scss/example/checkbox-form-multiple.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "checkbox-form-single": {
      name: "checkbox-form-single",
      type: "components:example",
      registryDependencies: ["checkbox","form"],
      component: React.lazy(() => import("@/registry/scss/example/checkbox-form-single")),
      source: "",
      files: ["registry/scss/example/checkbox-form-single.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "checkbox-with-text": {
      name: "checkbox-with-text",
      type: "components:example",
      registryDependencies: ["checkbox"],
      component: React.lazy(() => import("@/registry/scss/example/checkbox-with-text")),
      source: "",
      files: ["registry/scss/example/checkbox-with-text.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "collapsible-demo": {
      name: "collapsible-demo",
      type: "components:example",
      registryDependencies: ["collapsible"],
      component: React.lazy(() => import("@/registry/scss/example/collapsible-demo")),
      source: "",
      files: ["registry/scss/example/collapsible-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "combobox-demo": {
      name: "combobox-demo",
      type: "components:example",
      registryDependencies: ["command"],
      component: React.lazy(() => import("@/registry/scss/example/combobox-demo")),
      source: "",
      files: ["registry/scss/example/combobox-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "combobox-dropdown-menu": {
      name: "combobox-dropdown-menu",
      type: "components:example",
      registryDependencies: ["command","dropdown-menu","button"],
      component: React.lazy(() => import("@/registry/scss/example/combobox-dropdown-menu")),
      source: "",
      files: ["registry/scss/example/combobox-dropdown-menu.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "combobox-form": {
      name: "combobox-form",
      type: "components:example",
      registryDependencies: ["command","form"],
      component: React.lazy(() => import("@/registry/scss/example/combobox-form")),
      source: "",
      files: ["registry/scss/example/combobox-form.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "combobox-popover": {
      name: "combobox-popover",
      type: "components:example",
      registryDependencies: ["combobox","popover"],
      component: React.lazy(() => import("@/registry/scss/example/combobox-popover")),
      source: "",
      files: ["registry/scss/example/combobox-popover.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "combobox-responsive": {
      name: "combobox-responsive",
      type: "components:example",
      registryDependencies: ["combobox","popover","drawer"],
      component: React.lazy(() => import("@/registry/scss/example/combobox-responsive")),
      source: "",
      files: ["registry/scss/example/combobox-responsive.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "command-demo": {
      name: "command-demo",
      type: "components:example",
      registryDependencies: ["command"],
      component: React.lazy(() => import("@/registry/scss/example/command-demo")),
      source: "",
      files: ["registry/scss/example/command-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "command-dialog": {
      name: "command-dialog",
      type: "components:example",
      registryDependencies: ["command","dialog"],
      component: React.lazy(() => import("@/registry/scss/example/command-dialog")),
      source: "",
      files: ["registry/scss/example/command-dialog.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "context-menu-demo": {
      name: "context-menu-demo",
      type: "components:example",
      registryDependencies: ["context-menu"],
      component: React.lazy(() => import("@/registry/scss/example/context-menu-demo")),
      source: "",
      files: ["registry/scss/example/context-menu-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "data-table-demo": {
      name: "data-table-demo",
      type: "components:example",
      registryDependencies: ["data-table"],
      component: React.lazy(() => import("@/registry/scss/example/data-table-demo")),
      source: "",
      files: ["registry/scss/example/data-table-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "date-picker-demo": {
      name: "date-picker-demo",
      type: "components:example",
      registryDependencies: ["button","calendar","popover"],
      component: React.lazy(() => import("@/registry/scss/example/date-picker-demo")),
      source: "",
      files: ["registry/scss/example/date-picker-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "date-picker-form": {
      name: "date-picker-form",
      type: "components:example",
      registryDependencies: ["button","calendar","form","popover"],
      component: React.lazy(() => import("@/registry/scss/example/date-picker-form")),
      source: "",
      files: ["registry/scss/example/date-picker-form.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "date-picker-with-presets": {
      name: "date-picker-with-presets",
      type: "components:example",
      registryDependencies: ["button","calendar","popover","select"],
      component: React.lazy(() => import("@/registry/scss/example/date-picker-with-presets")),
      source: "",
      files: ["registry/scss/example/date-picker-with-presets.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "date-picker-with-range": {
      name: "date-picker-with-range",
      type: "components:example",
      registryDependencies: ["button","calendar","popover"],
      component: React.lazy(() => import("@/registry/scss/example/date-picker-with-range")),
      source: "",
      files: ["registry/scss/example/date-picker-with-range.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dialog-demo": {
      name: "dialog-demo",
      type: "components:example",
      registryDependencies: ["dialog"],
      component: React.lazy(() => import("@/registry/scss/example/dialog-demo")),
      source: "",
      files: ["registry/scss/example/dialog-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dialog-close-button": {
      name: "dialog-close-button",
      type: "components:example",
      registryDependencies: ["dialog","button"],
      component: React.lazy(() => import("@/registry/scss/example/dialog-close-button")),
      source: "",
      files: ["registry/scss/example/dialog-close-button.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "drawer-demo": {
      name: "drawer-demo",
      type: "components:example",
      registryDependencies: ["drawer"],
      component: React.lazy(() => import("@/registry/scss/example/drawer-demo")),
      source: "",
      files: ["registry/scss/example/drawer-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "drawer-dialog": {
      name: "drawer-dialog",
      type: "components:example",
      registryDependencies: ["drawer","dialog"],
      component: React.lazy(() => import("@/registry/scss/example/drawer-dialog")),
      source: "",
      files: ["registry/scss/example/drawer-dialog.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dropdown-menu-demo": {
      name: "dropdown-menu-demo",
      type: "components:example",
      registryDependencies: ["dropdown-menu"],
      component: React.lazy(() => import("@/registry/scss/example/dropdown-menu-demo")),
      source: "",
      files: ["registry/scss/example/dropdown-menu-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dropdown-menu-checkboxes": {
      name: "dropdown-menu-checkboxes",
      type: "components:example",
      registryDependencies: ["dropdown-menu","checkbox"],
      component: React.lazy(() => import("@/registry/scss/example/dropdown-menu-checkboxes")),
      source: "",
      files: ["registry/scss/example/dropdown-menu-checkboxes.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dropdown-menu-radio-group": {
      name: "dropdown-menu-radio-group",
      type: "components:example",
      registryDependencies: ["dropdown-menu","radio-group"],
      component: React.lazy(() => import("@/registry/scss/example/dropdown-menu-radio-group")),
      source: "",
      files: ["registry/scss/example/dropdown-menu-radio-group.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "hover-card-demo": {
      name: "hover-card-demo",
      type: "components:example",
      registryDependencies: ["hover-card"],
      component: React.lazy(() => import("@/registry/scss/example/hover-card-demo")),
      source: "",
      files: ["registry/scss/example/hover-card-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input-demo": {
      name: "input-demo",
      type: "components:example",
      registryDependencies: ["input"],
      component: React.lazy(() => import("@/registry/scss/example/input-demo")),
      source: "",
      files: ["registry/scss/example/input-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input-disabled": {
      name: "input-disabled",
      type: "components:example",
      registryDependencies: ["input"],
      component: React.lazy(() => import("@/registry/scss/example/input-disabled")),
      source: "",
      files: ["registry/scss/example/input-disabled.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input-file": {
      name: "input-file",
      type: "components:example",
      registryDependencies: ["input"],
      component: React.lazy(() => import("@/registry/scss/example/input-file")),
      source: "",
      files: ["registry/scss/example/input-file.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input-form": {
      name: "input-form",
      type: "components:example",
      registryDependencies: ["input","button","form"],
      component: React.lazy(() => import("@/registry/scss/example/input-form")),
      source: "",
      files: ["registry/scss/example/input-form.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input-with-button": {
      name: "input-with-button",
      type: "components:example",
      registryDependencies: ["input","button"],
      component: React.lazy(() => import("@/registry/scss/example/input-with-button")),
      source: "",
      files: ["registry/scss/example/input-with-button.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input-with-label": {
      name: "input-with-label",
      type: "components:example",
      registryDependencies: ["input","button","label"],
      component: React.lazy(() => import("@/registry/scss/example/input-with-label")),
      source: "",
      files: ["registry/scss/example/input-with-label.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input-with-text": {
      name: "input-with-text",
      type: "components:example",
      registryDependencies: ["input","button","label"],
      component: React.lazy(() => import("@/registry/scss/example/input-with-text")),
      source: "",
      files: ["registry/scss/example/input-with-text.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input-otp-demo": {
      name: "input-otp-demo",
      type: "components:example",
      registryDependencies: ["input-otp"],
      component: React.lazy(() => import("@/registry/scss/example/input-otp-demo")),
      source: "",
      files: ["registry/scss/example/input-otp-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input-otp-pattern": {
      name: "input-otp-pattern",
      type: "components:example",
      registryDependencies: ["input-otp"],
      component: React.lazy(() => import("@/registry/scss/example/input-otp-pattern")),
      source: "",
      files: ["registry/scss/example/input-otp-pattern.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input-otp-separator": {
      name: "input-otp-separator",
      type: "components:example",
      registryDependencies: ["input-otp"],
      component: React.lazy(() => import("@/registry/scss/example/input-otp-separator")),
      source: "",
      files: ["registry/scss/example/input-otp-separator.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input-otp-controlled": {
      name: "input-otp-controlled",
      type: "components:example",
      registryDependencies: ["input-otp"],
      component: React.lazy(() => import("@/registry/scss/example/input-otp-controlled")),
      source: "",
      files: ["registry/scss/example/input-otp-controlled.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "input-otp-form": {
      name: "input-otp-form",
      type: "components:example",
      registryDependencies: ["input-otp","form"],
      component: React.lazy(() => import("@/registry/scss/example/input-otp-form")),
      source: "",
      files: ["registry/scss/example/input-otp-form.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "label-demo": {
      name: "label-demo",
      type: "components:example",
      registryDependencies: ["label"],
      component: React.lazy(() => import("@/registry/scss/example/label-demo")),
      source: "",
      files: ["registry/scss/example/label-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "menubar-demo": {
      name: "menubar-demo",
      type: "components:example",
      registryDependencies: ["menubar"],
      component: React.lazy(() => import("@/registry/scss/example/menubar-demo")),
      source: "",
      files: ["registry/scss/example/menubar-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "navigation-menu-demo": {
      name: "navigation-menu-demo",
      type: "components:example",
      registryDependencies: ["navigation-menu"],
      component: React.lazy(() => import("@/registry/scss/example/navigation-menu-demo")),
      source: "",
      files: ["registry/scss/example/navigation-menu-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "pagination-demo": {
      name: "pagination-demo",
      type: "components:example",
      registryDependencies: ["pagination"],
      component: React.lazy(() => import("@/registry/scss/example/pagination-demo")),
      source: "",
      files: ["registry/scss/example/pagination-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "popover-demo": {
      name: "popover-demo",
      type: "components:example",
      registryDependencies: ["popover"],
      component: React.lazy(() => import("@/registry/scss/example/popover-demo")),
      source: "",
      files: ["registry/scss/example/popover-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "progress-demo": {
      name: "progress-demo",
      type: "components:example",
      registryDependencies: ["progress"],
      component: React.lazy(() => import("@/registry/scss/example/progress-demo")),
      source: "",
      files: ["registry/scss/example/progress-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "radio-group-demo": {
      name: "radio-group-demo",
      type: "components:example",
      registryDependencies: ["radio-group"],
      component: React.lazy(() => import("@/registry/scss/example/radio-group-demo")),
      source: "",
      files: ["registry/scss/example/radio-group-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "radio-group-form": {
      name: "radio-group-form",
      type: "components:example",
      registryDependencies: ["radio-group","form"],
      component: React.lazy(() => import("@/registry/scss/example/radio-group-form")),
      source: "",
      files: ["registry/scss/example/radio-group-form.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "resizable-demo": {
      name: "resizable-demo",
      type: "components:example",
      registryDependencies: ["resizable"],
      component: React.lazy(() => import("@/registry/scss/example/resizable-demo")),
      source: "",
      files: ["registry/scss/example/resizable-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "resizable-demo-with-handle": {
      name: "resizable-demo-with-handle",
      type: "components:example",
      registryDependencies: ["resizable"],
      component: React.lazy(() => import("@/registry/scss/example/resizable-demo-with-handle")),
      source: "",
      files: ["registry/scss/example/resizable-demo-with-handle.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "resizable-vertical": {
      name: "resizable-vertical",
      type: "components:example",
      registryDependencies: ["resizable"],
      component: React.lazy(() => import("@/registry/scss/example/resizable-vertical")),
      source: "",
      files: ["registry/scss/example/resizable-vertical.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "resizable-handle": {
      name: "resizable-handle",
      type: "components:example",
      registryDependencies: ["resizable"],
      component: React.lazy(() => import("@/registry/scss/example/resizable-handle")),
      source: "",
      files: ["registry/scss/example/resizable-handle.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "scroll-area-demo": {
      name: "scroll-area-demo",
      type: "components:example",
      registryDependencies: ["scroll-area"],
      component: React.lazy(() => import("@/registry/scss/example/scroll-area-demo")),
      source: "",
      files: ["registry/scss/example/scroll-area-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "scroll-area-horizontal-demo": {
      name: "scroll-area-horizontal-demo",
      type: "components:example",
      registryDependencies: ["scroll-area"],
      component: React.lazy(() => import("@/registry/scss/example/scroll-area-horizontal-demo")),
      source: "",
      files: ["registry/scss/example/scroll-area-horizontal-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "select-demo": {
      name: "select-demo",
      type: "components:example",
      registryDependencies: ["select"],
      component: React.lazy(() => import("@/registry/scss/example/select-demo")),
      source: "",
      files: ["registry/scss/example/select-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "select-scrollable": {
      name: "select-scrollable",
      type: "components:example",
      registryDependencies: ["select"],
      component: React.lazy(() => import("@/registry/scss/example/select-scrollable")),
      source: "",
      files: ["registry/scss/example/select-scrollable.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "select-form": {
      name: "select-form",
      type: "components:example",
      registryDependencies: ["select"],
      component: React.lazy(() => import("@/registry/scss/example/select-form")),
      source: "",
      files: ["registry/scss/example/select-form.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "separator-demo": {
      name: "separator-demo",
      type: "components:example",
      registryDependencies: ["separator"],
      component: React.lazy(() => import("@/registry/scss/example/separator-demo")),
      source: "",
      files: ["registry/scss/example/separator-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sheet-demo": {
      name: "sheet-demo",
      type: "components:example",
      registryDependencies: ["sheet"],
      component: React.lazy(() => import("@/registry/scss/example/sheet-demo")),
      source: "",
      files: ["registry/scss/example/sheet-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sheet-side": {
      name: "sheet-side",
      type: "components:example",
      registryDependencies: ["sheet"],
      component: React.lazy(() => import("@/registry/scss/example/sheet-side")),
      source: "",
      files: ["registry/scss/example/sheet-side.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "skeleton-demo": {
      name: "skeleton-demo",
      type: "components:example",
      registryDependencies: ["skeleton"],
      component: React.lazy(() => import("@/registry/scss/example/skeleton-demo")),
      source: "",
      files: ["registry/scss/example/skeleton-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "skeleton-card": {
      name: "skeleton-card",
      type: "components:example",
      registryDependencies: ["skeleton"],
      component: React.lazy(() => import("@/registry/scss/example/skeleton-card")),
      source: "",
      files: ["registry/scss/example/skeleton-card.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "slider-demo": {
      name: "slider-demo",
      type: "components:example",
      registryDependencies: ["slider"],
      component: React.lazy(() => import("@/registry/scss/example/slider-demo")),
      source: "",
      files: ["registry/scss/example/slider-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "sonner-demo": {
      name: "sonner-demo",
      type: "components:example",
      registryDependencies: ["sonner"],
      component: React.lazy(() => import("@/registry/scss/example/sonner-demo")),
      source: "",
      files: ["registry/scss/example/sonner-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "switch-demo": {
      name: "switch-demo",
      type: "components:example",
      registryDependencies: ["switch"],
      component: React.lazy(() => import("@/registry/scss/example/switch-demo")),
      source: "",
      files: ["registry/scss/example/switch-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "switch-form": {
      name: "switch-form",
      type: "components:example",
      registryDependencies: ["switch","form"],
      component: React.lazy(() => import("@/registry/scss/example/switch-form")),
      source: "",
      files: ["registry/scss/example/switch-form.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "table-demo": {
      name: "table-demo",
      type: "components:example",
      registryDependencies: ["table"],
      component: React.lazy(() => import("@/registry/scss/example/table-demo")),
      source: "",
      files: ["registry/scss/example/table-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tabs-demo": {
      name: "tabs-demo",
      type: "components:example",
      registryDependencies: ["tabs"],
      component: React.lazy(() => import("@/registry/scss/example/tabs-demo")),
      source: "",
      files: ["registry/scss/example/tabs-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "textarea-demo": {
      name: "textarea-demo",
      type: "components:example",
      registryDependencies: ["textarea"],
      component: React.lazy(() => import("@/registry/scss/example/textarea-demo")),
      source: "",
      files: ["registry/scss/example/textarea-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "textarea-disabled": {
      name: "textarea-disabled",
      type: "components:example",
      registryDependencies: ["textarea"],
      component: React.lazy(() => import("@/registry/scss/example/textarea-disabled")),
      source: "",
      files: ["registry/scss/example/textarea-disabled.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "textarea-form": {
      name: "textarea-form",
      type: "components:example",
      registryDependencies: ["textarea","form"],
      component: React.lazy(() => import("@/registry/scss/example/textarea-form")),
      source: "",
      files: ["registry/scss/example/textarea-form.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "textarea-with-button": {
      name: "textarea-with-button",
      type: "components:example",
      registryDependencies: ["textarea","button"],
      component: React.lazy(() => import("@/registry/scss/example/textarea-with-button")),
      source: "",
      files: ["registry/scss/example/textarea-with-button.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "textarea-with-label": {
      name: "textarea-with-label",
      type: "components:example",
      registryDependencies: ["textarea","label"],
      component: React.lazy(() => import("@/registry/scss/example/textarea-with-label")),
      source: "",
      files: ["registry/scss/example/textarea-with-label.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "textarea-with-text": {
      name: "textarea-with-text",
      type: "components:example",
      registryDependencies: ["textarea","label"],
      component: React.lazy(() => import("@/registry/scss/example/textarea-with-text")),
      source: "",
      files: ["registry/scss/example/textarea-with-text.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toast-demo": {
      name: "toast-demo",
      type: "components:example",
      registryDependencies: ["toast"],
      component: React.lazy(() => import("@/registry/scss/example/toast-demo")),
      source: "",
      files: ["registry/scss/example/toast-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toast-destructive": {
      name: "toast-destructive",
      type: "components:example",
      registryDependencies: ["toast"],
      component: React.lazy(() => import("@/registry/scss/example/toast-destructive")),
      source: "",
      files: ["registry/scss/example/toast-destructive.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toast-simple": {
      name: "toast-simple",
      type: "components:example",
      registryDependencies: ["toast"],
      component: React.lazy(() => import("@/registry/scss/example/toast-simple")),
      source: "",
      files: ["registry/scss/example/toast-simple.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toast-with-action": {
      name: "toast-with-action",
      type: "components:example",
      registryDependencies: ["toast"],
      component: React.lazy(() => import("@/registry/scss/example/toast-with-action")),
      source: "",
      files: ["registry/scss/example/toast-with-action.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toast-with-title": {
      name: "toast-with-title",
      type: "components:example",
      registryDependencies: ["toast"],
      component: React.lazy(() => import("@/registry/scss/example/toast-with-title")),
      source: "",
      files: ["registry/scss/example/toast-with-title.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle-group-demo": {
      name: "toggle-group-demo",
      type: "components:example",
      registryDependencies: ["toggle-group"],
      component: React.lazy(() => import("@/registry/scss/example/toggle-group-demo")),
      source: "",
      files: ["registry/scss/example/toggle-group-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle-group-disabled": {
      name: "toggle-group-disabled",
      type: "components:example",
      registryDependencies: ["toggle-group"],
      component: React.lazy(() => import("@/registry/scss/example/toggle-group-disabled")),
      source: "",
      files: ["registry/scss/example/toggle-group-disabled.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle-group-lg": {
      name: "toggle-group-lg",
      type: "components:example",
      registryDependencies: ["toggle-group"],
      component: React.lazy(() => import("@/registry/scss/example/toggle-group-lg")),
      source: "",
      files: ["registry/scss/example/toggle-group-lg.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle-group-outline": {
      name: "toggle-group-outline",
      type: "components:example",
      registryDependencies: ["toggle-group"],
      component: React.lazy(() => import("@/registry/scss/example/toggle-group-outline")),
      source: "",
      files: ["registry/scss/example/toggle-group-outline.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle-group-sm": {
      name: "toggle-group-sm",
      type: "components:example",
      registryDependencies: ["toggle-group"],
      component: React.lazy(() => import("@/registry/scss/example/toggle-group-sm")),
      source: "",
      files: ["registry/scss/example/toggle-group-sm.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle-group-single": {
      name: "toggle-group-single",
      type: "components:example",
      registryDependencies: ["toggle-group"],
      component: React.lazy(() => import("@/registry/scss/example/toggle-group-single")),
      source: "",
      files: ["registry/scss/example/toggle-group-single.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle-demo": {
      name: "toggle-demo",
      type: "components:example",
      registryDependencies: ["toggle"],
      component: React.lazy(() => import("@/registry/scss/example/toggle-demo")),
      source: "",
      files: ["registry/scss/example/toggle-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle-disabled": {
      name: "toggle-disabled",
      type: "components:example",
      registryDependencies: ["toggle"],
      component: React.lazy(() => import("@/registry/scss/example/toggle-disabled")),
      source: "",
      files: ["registry/scss/example/toggle-disabled.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle-lg": {
      name: "toggle-lg",
      type: "components:example",
      registryDependencies: ["toggle"],
      component: React.lazy(() => import("@/registry/scss/example/toggle-lg")),
      source: "",
      files: ["registry/scss/example/toggle-lg.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle-outline": {
      name: "toggle-outline",
      type: "components:example",
      registryDependencies: ["toggle"],
      component: React.lazy(() => import("@/registry/scss/example/toggle-outline")),
      source: "",
      files: ["registry/scss/example/toggle-outline.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle-sm": {
      name: "toggle-sm",
      type: "components:example",
      registryDependencies: ["toggle"],
      component: React.lazy(() => import("@/registry/scss/example/toggle-sm")),
      source: "",
      files: ["registry/scss/example/toggle-sm.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "toggle-with-text": {
      name: "toggle-with-text",
      type: "components:example",
      registryDependencies: ["toggle"],
      component: React.lazy(() => import("@/registry/scss/example/toggle-with-text")),
      source: "",
      files: ["registry/scss/example/toggle-with-text.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "tooltip-demo": {
      name: "tooltip-demo",
      type: "components:example",
      registryDependencies: ["tooltip"],
      component: React.lazy(() => import("@/registry/scss/example/tooltip-demo")),
      source: "",
      files: ["registry/scss/example/tooltip-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-blockquote": {
      name: "typography-blockquote",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-blockquote")),
      source: "",
      files: ["registry/scss/example/typography-blockquote.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-demo": {
      name: "typography-demo",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-demo")),
      source: "",
      files: ["registry/scss/example/typography-demo.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-h1": {
      name: "typography-h1",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-h1")),
      source: "",
      files: ["registry/scss/example/typography-h1.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-h2": {
      name: "typography-h2",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-h2")),
      source: "",
      files: ["registry/scss/example/typography-h2.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-h3": {
      name: "typography-h3",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-h3")),
      source: "",
      files: ["registry/scss/example/typography-h3.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-h4": {
      name: "typography-h4",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-h4")),
      source: "",
      files: ["registry/scss/example/typography-h4.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-inline-code": {
      name: "typography-inline-code",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-inline-code")),
      source: "",
      files: ["registry/scss/example/typography-inline-code.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-large": {
      name: "typography-large",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-large")),
      source: "",
      files: ["registry/scss/example/typography-large.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-lead": {
      name: "typography-lead",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-lead")),
      source: "",
      files: ["registry/scss/example/typography-lead.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-list": {
      name: "typography-list",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-list")),
      source: "",
      files: ["registry/scss/example/typography-list.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-muted": {
      name: "typography-muted",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-muted")),
      source: "",
      files: ["registry/scss/example/typography-muted.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-p": {
      name: "typography-p",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-p")),
      source: "",
      files: ["registry/scss/example/typography-p.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-small": {
      name: "typography-small",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-small")),
      source: "",
      files: ["registry/scss/example/typography-small.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "typography-table": {
      name: "typography-table",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/typography-table")),
      source: "",
      files: ["registry/scss/example/typography-table.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "mode-toggle": {
      name: "mode-toggle",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/mode-toggle")),
      source: "",
      files: ["registry/scss/example/mode-toggle.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "cards": {
      name: "cards",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/scss/example/cards")),
      source: "",
      files: ["registry/scss/example/cards/cards.tsx"],
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "dashboard-05": {
      name: "dashboard-05",
      type: "components:block",
      registryDependencies: ["badge","breadcrumb","button","card","dropdown-menu","input","pagination","progress","separator","sheet","table","tabs","tooltip"],
      component: React.lazy(() => import("@/registry/scss/block/dashboard-05")),
      source: "__registry__/scss/block/dashboard-05.tsx",
      files: ["registry/scss/block/dashboard-05.tsx"],
      category: "Application",
      subcategory: "Dashboard",
      chunks: [{
        name: "dashboard-05-chunk-0",
        description: "A card for an orders dashboard with a description and a button to create a new order.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-05-chunk-0")),
        file: "registry/scss/block/dashboard-05-chunk-0.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-05-chunk-1",
        description: "A stats card showing this week's total sales in USD, the percentage difference from last week, and a progress bar.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-05-chunk-1")),
        file: "registry/scss/block/dashboard-05-chunk-1.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-05-chunk-2",
        description: "A stats card showing this month's total sales in USD, the percentage difference from last month, and a progress bar.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-05-chunk-2")),
        file: "registry/scss/block/dashboard-05-chunk-2.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-05-chunk-3",
        description: "A table of recent orders showing the following columns: Customer, Type, Status, Date, and Amount.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-05-chunk-3")),
        file: "registry/scss/block/dashboard-05-chunk-3.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-05-chunk-4",
        description: "An order details card with order details, shipping information, customer information and payment information.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-05-chunk-4")),
        file: "registry/scss/block/dashboard-05-chunk-4.tsx",
        container: {
          className: "undefined"
        }
      }]
    },
    "dashboard-06": {
      name: "dashboard-06",
      type: "components:block",
      registryDependencies: ["badge","breadcrumb","button","card","dropdown-menu","input","sheet","table","tabs","tooltip"],
      component: React.lazy(() => import("@/registry/scss/block/dashboard-06")),
      source: "__registry__/scss/block/dashboard-06.tsx",
      files: ["registry/scss/block/dashboard-06.tsx"],
      category: "Application",
      subcategory: "Dashboard",
      chunks: [{
        name: "dashboard-06-chunk-0",
        description: "A list of products in a table with actions. Each row has an image, name, status, price, total sales, created at and actions.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-06-chunk-0")),
        file: "registry/scss/block/dashboard-06-chunk-0.tsx",
        container: {
          className: "undefined"
        }
      }]
    },
    "dashboard-07": {
      name: "dashboard-07",
      type: "components:block",
      registryDependencies: ["badge","breadcrumb","button","card","dropdown-menu","input","pagination","progress","separator","sheet","table","tabs","tooltip"],
      component: React.lazy(() => import("@/registry/scss/block/dashboard-07")),
      source: "__registry__/scss/block/dashboard-07.tsx",
      files: ["registry/scss/block/dashboard-07.tsx"],
      category: "Application",
      subcategory: "Dashboard",
      chunks: [{
        name: "dashboard-07-chunk-0",
        description: "A card with a form to edit the product details",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-07-chunk-0")),
        file: "registry/scss/block/dashboard-07-chunk-0.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-07-chunk-1",
        description: "A card with a form to edit the product stock and variants",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-07-chunk-1")),
        file: "registry/scss/block/dashboard-07-chunk-1.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-07-chunk-2",
        description: "A card with a form to edit the product category and subcategory",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-07-chunk-2")),
        file: "registry/scss/block/dashboard-07-chunk-2.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-07-chunk-3",
        description: "A card with a form to edit the product status",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-07-chunk-3")),
        file: "registry/scss/block/dashboard-07-chunk-3.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-07-chunk-4",
        description: "A card with a form to upload product images",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-07-chunk-4")),
        file: "registry/scss/block/dashboard-07-chunk-4.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-07-chunk-5",
        description: "A card with a call to action to archive the product",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-07-chunk-5")),
        file: "registry/scss/block/dashboard-07-chunk-5.tsx",
        container: {
          className: "undefined"
        }
      }]
    },
    "dashboard-04": {
      name: "dashboard-04",
      type: "components:block",
      registryDependencies: ["button","card","dropdown-menu","input"],
      component: React.lazy(() => import("@/registry/scss/block/dashboard-04")),
      source: "__registry__/scss/block/dashboard-04.tsx",
      files: ["registry/scss/block/dashboard-04.tsx"],
      category: "Application",
      subcategory: "Dashboard",
      chunks: [{
        name: "dashboard-04-chunk-0",
        description: "A sidebar navigation with links to general, security, integrations, support, organizations, and advanced settings.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-04-chunk-0")),
        file: "registry/scss/block/dashboard-04-chunk-0.tsx",
        container: {
          className: "chunk-container after:right-0"
        }
      },{
        name: "dashboard-04-chunk-1",
        description: "A form to update the store name.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-04-chunk-1")),
        file: "registry/scss/block/dashboard-04-chunk-1.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-04-chunk-2",
        description: "A form to update the plugins directory with a checkbox to allow administrators to change the directory.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-04-chunk-2")),
        file: "registry/scss/block/dashboard-04-chunk-2.tsx",
        container: {
          className: "undefined"
        }
      }]
    },
    "dashboard-03": {
      name: "dashboard-03",
      type: "components:block",
      registryDependencies: ["badge","button","drawer","input","label","select","textarea","tooltip"],
      component: React.lazy(() => import("@/registry/scss/block/dashboard-03")),
      source: "__registry__/scss/block/dashboard-03.tsx",
      files: ["registry/scss/block/dashboard-03.tsx"],
      category: "Application",
      subcategory: "Dashboard",
      chunks: [{
        name: "dashboard-03-chunk-0",
        description: "A settings form a configuring an AI model and messages.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-03-chunk-0")),
        file: "registry/scss/block/dashboard-03-chunk-0.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-03-chunk-1",
        description: "A form for sending a message to an AI chatbot. The form has a textarea and buttons to upload files and record audio.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-03-chunk-1")),
        file: "registry/scss/block/dashboard-03-chunk-1.tsx",
        container: {
          className: "undefined"
        }
      }]
    },
    "dashboard-02": {
      name: "dashboard-02",
      type: "components:block",
      registryDependencies: ["badge","button","card","dropdown-menu","input"],
      component: React.lazy(() => import("@/registry/scss/block/dashboard-02")),
      source: "__registry__/scss/block/dashboard-02.tsx",
      files: ["registry/scss/block/dashboard-02.tsx"],
      category: "Application",
      subcategory: "Dashboard",
      chunks: [{
        name: "dashboard-02-chunk-0",
        description: "A card with a call to action",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-02-chunk-0")),
        file: "registry/scss/block/dashboard-02-chunk-0.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-02-chunk-1",
        description: "An empty state showing no products with a heading, description and a call to action to add a product.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-02-chunk-1")),
        file: "registry/scss/block/dashboard-02-chunk-1.tsx",
        container: {
          className: "undefined"
        }
      }]
    },
    "dashboard-01": {
      name: "dashboard-01",
      type: "components:block",
      registryDependencies: ["button","dropdown-menu","input","sheet"],
      component: React.lazy(() => import("@/registry/scss/block/dashboard-01")),
      source: "__registry__/scss/block/dashboard-01.tsx",
      files: ["registry/scss/block/dashboard-01.tsx"],
      category: "Application",
      subcategory: "Dashboard",
      chunks: [{
        name: "dashboard-01-chunk-0",
        description: "A card showing the total revenue in USD and the percentage difference from last month.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-01-chunk-0")),
        file: "registry/scss/block/dashboard-01-chunk-0.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-01-chunk-1",
        description: "A card showing the total subscriptions and the percentage difference from last month.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-01-chunk-1")),
        file: "registry/scss/block/dashboard-01-chunk-1.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-01-chunk-2",
        description: "A card showing the total sales and the percentage difference from last month.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-01-chunk-2")),
        file: "registry/scss/block/dashboard-01-chunk-2.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-01-chunk-3",
        description: "A card showing the total active users and the percentage difference from last hour.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-01-chunk-3")),
        file: "registry/scss/block/dashboard-01-chunk-3.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-01-chunk-4",
        description: "A card showing a table of recent transactions with a link to view all transactions.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-01-chunk-4")),
        file: "registry/scss/block/dashboard-01-chunk-4.tsx",
        container: {
          className: "undefined"
        }
      },{
        name: "dashboard-01-chunk-5",
        description: "A card showing a list of recent sales with customer names and email addresses.",
        component: React.lazy(() => import("@/registry/scss/block/dashboard-01-chunk-5")),
        file: "registry/scss/block/dashboard-01-chunk-5.tsx",
        container: {
          className: "undefined"
        }
      }]
    },
    "authentication-01": {
      name: "authentication-01",
      type: "components:block",
      registryDependencies: ["button","card","input","label"],
      component: React.lazy(() => import("@/registry/scss/block/authentication-01")),
      source: "__registry__/scss/block/authentication-01.tsx",
      files: ["registry/scss/block/authentication-01.tsx"],
      category: "Authentication",
      subcategory: "Login",
      chunks: []
    },
    "authentication-02": {
      name: "authentication-02",
      type: "components:block",
      registryDependencies: ["button","card","input","label"],
      component: React.lazy(() => import("@/registry/scss/block/authentication-02")),
      source: "__registry__/scss/block/authentication-02.tsx",
      files: ["registry/scss/block/authentication-02.tsx"],
      category: "Authentication",
      subcategory: "Login",
      chunks: []
    },
    "authentication-03": {
      name: "authentication-03",
      type: "components:block",
      registryDependencies: ["button","card","input","label"],
      component: React.lazy(() => import("@/registry/scss/block/authentication-03")),
      source: "__registry__/scss/block/authentication-03.tsx",
      files: ["registry/scss/block/authentication-03.tsx"],
      category: "Authentication",
      subcategory: "Login",
      chunks: []
    },
    "authentication-04": {
      name: "authentication-04",
      type: "components:block",
      registryDependencies: ["button","card","input","label"],
      component: React.lazy(() => import("@/registry/scss/block/authentication-04")),
      source: "__registry__/scss/block/authentication-04.tsx",
      files: ["registry/scss/block/authentication-04.tsx"],
      category: "Authentication",
      subcategory: "Login",
      chunks: []
    },
  },
}
